### ISSUE TITLE
file Glove/glove.840B.300d.txt.gz not found

### ISSUE THREAD

**Issue by chengchingwen** [allenai/scitail#4]
I try to run `sh scripts/train_models.sh` and get 
```python
FileNotFoundError: file Glove/glove.840B.300d.txt.gz not found
```

where should I put the glove pre-trained word vectors ?

btw, nlp.stanford.edu only have zip file glove now.

**Comment by chengchingwen** [comment]
After I change the pre-train model path and unzip & gzip the glove vectors manually, I get some warning like this
```
2018-02-06 11:32:59,266 - WARNING - allennlp.modules.token_embedders.embedding - Found line with wrong number of dimensions (ex
pected 300, was 299): b'\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0\xc2\xa0 0.5478 0.18474 0.14057 -0.92452 -0.90097 -0.11
618 -0.53059 0.34625 0.15681 -1.6009 0.87718 -0.43912 0.62262 1.0086 -0.24369 -0.073876 0.15422 -1.4411 0.04154 0.21189 -0.0780 
...
```
Is this normal ?

**Comment by tusharkhot** [comment]
Thanks for pointing this out. I will add instructions for the location of the Glove embeddings. 

Regarding the waring, yes it is expected. We use AllenNLP for reading Glove embeddings and it gives a warning when the num. of dim. in the file doesn't match the expected vector dim. There are few entries in Glove 840B with this issue.

**Comment by tusharkhot** [comment]
Sorry it took me a while to get to these. The README is now updated in #7.
