### ISSUE TITLE
Predictor for tree attention model 

### ISSUE THREAD

**Issue by chengchingwen** [allenai/scitail#5]
I try to write a predictor for dgem following [allennlp's tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md) and get a few errors. I'm not sure what cause these problems, so I post these issues here for now.

First, I follow the [Making Predictions and Creating a Demo tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md) and write

```python
@Predictor.register('tree_attention')
class TreeAttentionPredictor(Predictor):
    """"Predictor wrapper for the tree attention entailment classifier"""
    @overrides
    def _json_to_instance(self, json_dict: JsonDict) -> Tuple[Instance, JsonDict]:
        premise = json_dict['premise']
        hypothesis = json_dict['hypothesis']
        hypothesis_structure = json_dict['hypothesis_structure']
        label = json_dict['label']
        instance = self._dataset_reader.text_to_instance(premise, hypothesis, hypothesis_structure,
                                                       label)

        # label_dict will be like {0: "ACL", 1: "AI", ...}
        label_dict = self._model.vocab.get_index_to_token_vocabulary('labels')
        # Convert it to list ["ACL", "AI", ...]
        all_labels = [label_dict[i] for i in range(len(label_dict))]

        return instance , {"all_labels": all_labels}
```
However, 
```
> /home/peter/work/scitail/scienv/lib/python3.6/site-packages/allennlp/service/predictors/predictor.py(17)predict_json()
-> def predict_json(self, inputs: JsonDict, cuda_device: int = -1) -> JsonDict:
(Pdb) ll
 17  ->     def predict_json(self, inputs: JsonDict, cuda_device: int = -1) -> JsonDict:
 18             instance = self._json_to_instance(inputs)
 19             outputs = self._model.forward_on_instance(instance, cuda_device)
 20             return sanitize(outputs)

```

The return values seem not to be assigned correctly. 
Besides, the registered Predictor cannot be found.
```
Traceback (most recent call last):
  File "run.py", line 17, in <module>
    main(prog="python -m scitail.run")
  File "/home/peter/work/scitail/scienv/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/peter/work/scitail/scienv/lib/python3.6/site-packages/allennlp/commands/predict.py", line 86, in predict_inner
    predictor = _get_predictor(args, predictors)
  File "/home/peter/work/scitail/scienv/lib/python3.6/site-packages/allennlp/commands/predict.py", line 63, in _get_predictor
    raise ConfigurationError("no known predictor for model type {}".format(model_type))
allennlp.common.checks.ConfigurationError: 'no known predictor for model type tree_attention'
```

so I manually override in main function
```python
if __name__ == "__main__":
    main(prog="python -m scitail.run", predictor_overrides={"tree_attention": "tree_attention"})
```

I'm not sure this is a correct way to do it.
But In my expectation, at least in [the allennlp-as-a-library-example](https://github.com/allenai/allennlp-as-a-library-example/tree/0.4.0), the manual config seem not to be necessary.

**Comment by tusharkhot** [comment]
For replicability, I am using a specific AllenNLP commit in this library. Unfortunately, this differs from the current AllenNLP commit and the linked tutorial. So the tutorial instructions won't directly translate to this version. I can write a`Predictor` for the DGEM model but it would help to know what you intend to do with the predictor (e.g. are you trying to create a web demo?).

**Comment by chengchingwen** [comment]
I'm trying to do some error analysis on SciTail.
Currently I dump the result with the `Predictor` and compare with the input file with some simple code. 

Do you have any function inside `allennlp` or this repo that can do these stuff already? 

I saw there was a error analysis section on the SciTail paper, but I can't find a way to so without  writing a `Predictor`.

**Comment by tusharkhot** [comment]
I have added new predictors and a `predict_models.sh` script that should help with this in #7. Hopefully this makes it easier to look at the predictions.

**Comment by chengchingwen** [comment]
Thanks! looks great!
