### ISSUE TITLE
Hard to find link to download scitail from http://data.allenai.org/scitail

### ISSUE THREAD

**Issue by azpoliak** [allenai/scitail#6]
Not sure if this is the right place to post this but I had a hard time figuring out how to download the data from the website. The bottom of the webpage says `To download the dataset, click the Download button in the upper-right.` The download button is a pencil and when hovering on the button, the text says `edit this page`. I found this github repo by accidentally clicking on the "edit" button on the [webpage ](http://data.allenai.org/scitail/train/) with the training examples.

Also, the link on the button is broken since it redirects to an [empty page on github](https://github.com/allenai/%3Cyour%20repo%3E/edit/master/docs/index.md). I only found the url for the data once I poked around the repo and found the [download_data.sh](https://github.com/allenai/scitail/blob/master/scripts/download_data.sh) script.

**Comment by tusharkhot** [comment]
Thanks for pointing this out. The "Download" button for our dataset pages need to be clearer. `To download the dataset, click the Download button in the upper-right.` is referring to the orange button on the top tab and not the pencil/edit page button. 

I have added the link to the README now, so it should be easier to find.

**Comment by azpoliak** [comment]
Can't miss that new orange button! Thanks for adding it.
