### ISSUE TITLE
OpenIE

### ISSUE THREAD

**Issue by nooralahzadeh** [allenai/scitail#9]
could you elaborate more about how you create the OPenIE graph.
Any sample code!

**Comment by tusharkhot** [comment]
It is described in "Graph Definition" section of the [paper](http://ai2-website.s3.amazonaws.com/publications/scitail-aaai-2018_cameraready.pdf). Did you have any specific questions regarding the process ?

**Comment by nooralahzadeh** [comment]
Hi, I read it and find out the detail. Thanks
